<a href="https://colab.research.google.com/github/laxmishbadiger/pytorch/blob/main/pytorch_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import torch
import numpy as np

In [7]:
# LISTS

In [11]:
my_list = [[1,2,32],[2,3,4,4]]
my_list


[[1, 2, 32], [2, 3, 4, 4]]

In [12]:
# Numpy Array

In [28]:
nps = np.random.rand(3, 4)
nps

array([[0.0313744 , 0.15496676, 0.04040289, 0.41995614],
       [0.75036663, 0.0322491 , 0.72641099, 0.04150267],
       [0.2095174 , 0.43723959, 0.6022218 , 0.36133481]])

In [32]:
nps.dtype

dtype('float64')

In [30]:
# Tensors

In [31]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[-0.4307, -0.5382,  1.1905,  0.2128],
        [-0.6723,  0.9253, -1.9124,  0.2252],
        [-1.0077,  1.5738, -0.3265, -0.1612]])

In [40]:
tensor_3d = torch.randn(10,3, 4)
tensor_3d


tensor([[[ 7.8111e-01, -1.7324e+00, -7.7206e-01, -2.3818e+00],
         [-1.4016e+00,  1.1157e-01, -1.4324e+00, -1.6501e+00],
         [ 5.3913e-01,  1.5758e+00, -7.2668e-03,  8.4478e-01]],

        [[ 5.3500e-01, -1.0203e+00, -2.8216e-01, -1.0085e-01],
         [-2.7628e-01,  2.0291e-01,  3.0220e-01,  7.2007e-01],
         [-4.3196e-03,  1.1000e-01, -4.3030e-01,  1.1507e-01]],

        [[ 4.9633e-01,  8.1350e-01,  4.3038e-01, -2.9115e-01],
         [ 6.5554e-03,  1.1120e+00, -2.7174e-01, -2.1030e-01],
         [-2.0656e+00,  1.3232e-01, -5.0616e-02,  1.4015e-01]],

        [[-1.0395e+00,  1.1303e+00, -1.0378e-01, -5.2458e-01],
         [-1.0950e+00,  7.2471e-01,  1.4068e+00, -4.5671e-01],
         [ 3.3127e-04,  4.4504e-01,  2.1146e+00, -1.2849e+00]],

        [[-3.9989e-01, -4.2529e-01,  7.9545e-01,  1.9320e+00],
         [ 9.0258e-01, -1.8728e-02,  5.5578e-01, -5.7063e-01],
         [ 1.1904e+00, -5.4840e-01, -5.7739e-01,  8.9306e-01]],

        [[-3.0258e-01,  1.4772e+00,  6.9144e-

In [41]:
print(tensor_3d.dtype)

torch.float32


In [42]:
# Numpy array to tensor array

In [38]:
my_tensor =  torch.tensor(nps)
my_tensor

tensor([[0.0314, 0.1550, 0.0404, 0.4200],
        [0.7504, 0.0322, 0.7264, 0.0415],
        [0.2095, 0.4372, 0.6022, 0.3613]], dtype=torch.float64)